[tool.poetry]
name = "dea"
version = "0.1.0"
description = "Interactive Dublin Residential Retrofit Map"
authors = ["Rowan Molony <rowan.molony@codema.ie>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
bokeh = "~2.2"
icontract = "^2.5.4"
streamlit = "^0.88.0"
streamlit-bokeh-events = "^0.1.2"
pandas = "^1.3.3"
geopandas = "^0.9.0"
s3fs = "^2021.8.1"
rcbm = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
